# -*- coding: utf-8 -*-
"""mnist_write_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kwo2ZBoFzssdVQHBXMawgLo6DX1TVKtO
"""

import streamlit as st
import numpy as np
import cv2
import joblib
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model, Model 
from streamlit_drawable_canvas import st_canvas

# --- 1. Page Config & Title ---
st.set_page_config(page_title="MNIST Model Comparison", layout="wide")
st.title("Draw a Digit: Comparing Models")
st.write("Draw a number from 0-9 below and see how different models interpret it!")

# --- 2. Load Models (Cached for speed) ---
@st.cache_resource
def load_all_models():
    # Load the Scikit-Learn models
    rf = joblib.load('rf_model_mnistdataset.joblib')
    l1 = joblib.load('l1_model_mnistdataset.joblib')
    #en = joblib.load('en_model_mnistdataset.joblib')

    # Load the Keras Sequential Models
    nn1 = load_model('L1R128_L2sig128_L3smax10.keras')
    nn2 = load_model('L1R264_L2sig264_L3smax10.keras')

    return rf, l1, nn1, nn2

# Fixed the extra comma here!
rf_model, l1_model, nn_model_1, nn_model_2 = load_all_models()

# --- 3. UI Layout ---
col1, col2 = st.columns([1, 2])

with col1:
    st.markdown("### Drawing Pad")
    # Create an interactive canvas
    canvas_result = st_canvas(
        fill_color="black",
        stroke_width=15, # Thick brush for better 28x28 scaling
        stroke_color="white",
        background_color="black",
        height=280,
        width=280,
        drawing_mode="freedraw",
        key="canvas",
    )

    model_choice = st.selectbox(
        "Choose your model:",
        ("Random Forest", "L1- Lasso Model", "Sequential NN (Model 1)", "Sequential NN (Model 2)")
    )

    predict_btn = st.button("Predict Digit", type="primary")

with col2:
    st.markdown("### Prediction Results")

    # --- 4. Process Drawing & Predict ---
    if predict_btn and canvas_result.image_data is not None:
        # The canvas outputs a 280x280 RGBA image. We need it to be 28x28 Grayscale.
        img_array = canvas_result.image_data

        # Convert to grayscale
        gray_image = cv2.cvtColor(img_array, cv2.COLOR_RGBA2GRAY)

        # Resize from 280x280 down to 28x28
        resized_image = cv2.resize(gray_image, (28, 28), interpolation=cv2.INTER_AREA)

        # Flatten for models (1, 784) and normalize
        input_data = resized_image.reshape(1, 784) / 255.0

        # --- Model Prediction Logic ---
        if model_choice == "Random Forest":
            prediction = rf_model.predict(input_data)[0]
            st.success(f"### Random Forest predicts: **{prediction}**")

        elif model_choice == "L1- Lasso Model":
            prediction = l1_model.predict(input_data)[0]
            st.success(f"### L1- Lasso Model predicts: **{prediction}**")

        elif model_choice == "Sequential NN (Model 1)":
            # 1. Standard Prediction
            probabilities = nn_model_1.predict(input_data.reshape(1,28,28))[0]
            prediction = np.argmax(probabilities)
            st.success(f"### Sequential NN (Model 1) predicts: **{prediction}**")
            st.write(f"Confidence: {probabilities[prediction]:.2%}")
            st.progress(float(probabilities[prediction]))
            
            # 2. Visualize Neural Activations Manually
            st.markdown("### Inside the Network: Neuron Activations")
            
            # Start with the input image
            x = input_data.reshape(1, 28, 28)
            
            # Push the data through each layer one-by-one
            for i, layer in enumerate(nn_model_1.layers):
                x = layer(x) # Eagerly calculate this layer's output
                activation_data = x.numpy() # Convert Tensor to a NumPy array for Streamlit
                
                st.caption(f"Layer {i+1}: {layer.name} ({activation_data.shape[-1]} neurons)")
                
                # If it's a flattened/dense layer, draw the bar chart
                if len(activation_data.shape) == 2:
                    st.bar_chart(activation_data[0])

        elif model_choice == "Sequential NN (Model 2)":
            # 1. Standard Prediction
            probabilities = nn_model_2.predict(input_data.reshape(1,28,28))[0]
            prediction = np.argmax(probabilities)
            st.success(f"### Sequential NN (Model 2) predicts: **{prediction}**")
            st.write(f"Confidence: {probabilities[prediction]:.2%}")
            st.progress(float(probabilities[prediction]))
            
            # 2. Visualize Neural Activations Manually
            st.markdown("### Inside the Network: Neuron Activations")
            
            x = input_data.reshape(1, 28, 28)
            
            for i, layer in enumerate(nn_model_2.layers):
                x = layer(x)
                activation_data = x.numpy()
                
                st.caption(f"Layer {i+1}: {layer.name} ({activation_data.shape[-1]} neurons)")
                
                if len(activation_data.shape) == 2:
                    st.bar_chart(activation_data[0])